services:
  automadoka:
    image: ghcr.io/cc004/automadoka:latest
    ports:
      - 13200:13200
    restart: always
    container_name: automadoka
    volumes:
      - ./cache:/app/cache
    # use proxy:
    # environment:
    #  - http_proxy=http://{your_proxy_host}:{your_proxy_port}
    #  - https_proxy=http://{your_proxy_host}:{your_proxy_port}
